@startuml
entity "theatres" as T
entity "auditoriums" as A
entity "movies" as M
entity "shows" as S
entity "seats" as SE
entity "seat_availability" as SA
entity "bookings" as B
T ||--o{ A
A ||--o{ SE
A ||--o{ S
M ||--o{ S
S ||--o{ SA
SE ||--o{ SA
SA ||--o{ B
@enduml
