-- Oracle schema DDL
CREATE TABLE theatres (
  theatre_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR2(200), city VARCHAR2(100), address VARCHAR2(400)
);
CREATE TABLE auditoriums (
  auditorium_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  theatre_id NUMBER REFERENCES theatres(theatre_id),
  name VARCHAR2(100), capacity NUMBER
);
CREATE TABLE movies (
  movie_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  title VARCHAR2(300), duration_minutes NUMBER, rating VARCHAR2(10), language VARCHAR2(50)
);
CREATE TABLE shows (
  show_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  movie_id NUMBER REFERENCES movies(movie_id),
  auditorium_id NUMBER REFERENCES auditoriums(auditorium_id),
  show_time TIMESTAMP, price NUMBER(8,2)
);
CREATE TABLE seats (
  seat_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  auditorium_id NUMBER REFERENCES auditoriums(auditorium_id),
  seat_label VARCHAR2(20), seat_type VARCHAR2(20)
);
CREATE TABLE seat_availability (
  seat_avail_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  show_id NUMBER REFERENCES shows(show_id),
  seat_id NUMBER REFERENCES seats(seat_id),
  status VARCHAR2(20)
);
CREATE TABLE bookings (
  booking_id NUMBER PRIMARY KEY,
  show_id NUMBER REFERENCES shows(show_id),
  seat_avail_id NUMBER REFERENCES seat_availability(seat_avail_id),
  customer_name VARCHAR2(200), customer_phone VARCHAR2(20),
  booked_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  amount NUMBER(8,2), status VARCHAR2(20)
);
CREATE SEQUENCE seq_booking_id START WITH 1000 INCREMENT BY 1;
